### ISSUE TITLE
Can not listen on an unix socket in /cplayground which is mapped as a shared folder in VirutalBox

### ISSUE THREAD

**Issue by wxw-matt** [reberhardt7/cplayground#48]
I found some information from other repo, someone said that the UNIX socket file can not be created in a shared folder and I verified that was true.

Any plan on this issue?

**Comment by wxw-matt** [comment]
For example, could the unix socket file be created in the tmp folder?

**Comment by wxw-matt** [comment]
Error backtrace:
[2020-11-14T14:58:59+1000] [LOG]    [VYMVa2v-5u10Bc7TAAAB] Run logged with ID 10
[2020-11-14T14:58:59+1000] [LOG]    [VYMVa2v-5u10Bc7TAAAB] Saving code to /cplayground/data/36abd0dd-b813-4e32-b50c-03ec89685e51
[2020-11-14T14:58:59+1000] [ERROR]  Error: listen EPERM: operation not permitted /cplayground/data/36abd0dd-b813-4e32-b50c-03ec89685e51-gdb.sock
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1463:5)
    at /cplayground/src/server/container.ts:143:30
    at new Promise (<anonymous>)
    at Container.initializeDebugSocket (/cplayground/src/server/container.ts:142:16)
    at new Container (/cplayground/src/server/container.ts:118:33)
    at /cplayground/src/server/socket-connection.ts:163:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
